### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by cpb2948** [badleyy/rtapi#5]
@dadleyy What do you think of the token based authentication?

**Comment by dadleyy** [comment]
mixed feelings. I like it because its forward thinking - native clients would need that kind of thing. I don't like it because our browser side application could just use cookies with laravel's [session](http://laravel.com/docs/5.1/session) stuff which would be _much_ easier. maybe try implementing both?

**Comment by cpb2948** [comment]
yeah its gonna take a little bit of dev on the client side to interact using the tokens. I can look into implementing both.

**Comment by dadleyy** [comment]
make a jira ticket for it!

> allow consumers of the api to authenticate using cookie based session model
